---
- hosts: all
  tasks:
  - name: Execute command in Windows
    win_shell: net localgroup Administrators bupa\sgdi /add
    args:
        executable: cmd
    register: out

  - debug: var=out.stdout_lines
