---
- hosts: all
  gather_facts: false
  tasks:
  - name: activar DC 20.X
    win_shell: '"C:\Program Files (x86)\Symantec\Symantec Endpoint Protection\smc" smc -stop'
    args:
        executable: cmd
    register: out
  - debug: var=out.stdout_lines
