---
- name: windows change password
  hosts: all
  vars:
    usr_name: 'infra'
    usr_password: 'PactoDeSangre.2017'
  tasks:
    - name: change password
      ansible.windows.win_user:
        name: "{{ usr_name }}"
        password: "{{ usr_password }}"
