---
- name: descargar sgdi
  hosts: all
  vars:

  tasks:
    - name: descargar archivo
      win_get_url:
        URL: https://content.lansweeper.com/lsagent-windows/
        dest: 'C:\Software Base\LsAgent-windows.exe'
        force: True
