---
- hosts: all
  tasks:
  - name: Execute command in Windows
    win_shell: del /f "C:\Software Base\Topia_CMD_Setup_x64.msi"
    args:
        executable: cmd
    register: out

  - debug: var=out.stdout_lines
