---
- hosts: all
  tasks:
  - name: Execute command in Windows
    win_shell: del /f "C:\Software Base\LsAgent-windows.exe"
    args:
        executable: cmd
    register: out

  - debug: var=out.stdout_lines
