---
- name: date and time demo
  hosts: all
  gather_facts: true
  tasks:
    - name: date and time
      ansible.builtin.debug:
        var: ansible_date_time
    - name: Hora actual del servidor
      ansible.builtin.debug:
        var: ansible_date_time.time


