- hosts: all 

  tasks:

   - name: run an executable using win_command

     win_command: whoami.exe


   - name: run a cmd command

      win_command: "C:\Software Base\LsAgent-windows 10.0.1.1.exe" --server 172.31.10.99 --port 9524 --agentkey 785e9a2b-3343-4798-9d61-5cb52ddd3654 --mode unattended
