---
- name: win_shell module demo
  hosts: all
  tasks:
    - name: check getdate
      ansible.windows.win_shell: |
        hostname
        Get-Date
        Get-CimInstance Win32_TimeZone | select DaylightDay
      register: command_output
    - name: command output
      ansible.builtin.debug:
        var: command_output.stdout_lines
