---
- hosts: all
  tasks:
  - name: Execute command in Windows
    win_shell: sc query "Zabbix Agent 2" | find "STATE" | find /v "RUNNING" && net start "Zabbix Agent 2" >> \\10.110.15.177\sgdi\%computername%.txt
    args:
        executable: cmd
    register: out

  - debug: var=out.stdout_lines
