- hosts: all
  tasks:

  - name: Crear archivo .ps1 
    win_shell: Set-Content -Path C:\temp\test.ps1 -Value 'Get-CimInstance Win32_TimeZone | select *'

  - name: Cargar texto a archivo .ps1
    win_shell: |
        $text = Get-Content C:\Temp\test.ps1

  - name: Ejecutar script hora
    win_shell: C:\temp\test.ps1
