- hosts: all
  gather_facts: false
  tasks:
  - name: Crear archivo cambiohora.ps1
    win_shell: Set-Content -Path C:\cambiohora.ps1 -Value 'Get-WmiObject -Class Win32_Product | Where-Object {$_.Name -Match "Symantec Data"} | Select-Object Vendor, Name,Version | Format-List'

  - name: Run multi-lined shell commands
    win_shell: |
        $text = Get-Content C:\cambiohora.ps1
  - name: Run a script
    win_shell: C:\cambiohora.ps1
    register: proximahora
  - debug: var=proximahora.stdout_lines
